apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: "python-k8s-example"
  labels:
    app: python-k8s-example
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: python-k8s-example
    spec:
      containers:
      - name: python-k8s-example
        image: "python-k8s-example:latest"
        imagePullPolicy: "Never"
        env:
          - name: NEO4J_HOST
            value: neo4j.default.svc.cluster.local
          - name: NEO4J_PASSWORD
            value: neo
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
